export const CRYPTO_CONFIG = {
    SYMMETRIC_ALGORITHM: 'AES-GCM',
    SYMMETRIC_KEY_LENGTH: 256,
    ASYMMETRIC_ALGORITHM: 'ECDH',
    ASYMMETRIC_CURVE: 'P-256',
    SIGNATURE_ALGORITHM: 'ECDSA',
    HASH_ALGORITHM: 'SHA-256',
};
export const STORAGE_CONFIG = {
    DB_NAME: 'partage-db',
    DB_VERSION: 1,
};
